/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => NoteToWikiJSPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/settings.ts
var import_obsidian2 = require("obsidian");

// src/wikijs-api.ts
var import_obsidian = require("obsidian");
var WikiJSAPI = class {
  constructor(settings) {
    this.settings = settings;
  }
  async makeGraphQLRequest(query, variables) {
    const response = await (0, import_obsidian.requestUrl)({
      url: `${this.settings.wikiUrl}/graphql`,
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${this.settings.apiToken}`
      },
      body: JSON.stringify([{
        operationName: null,
        query,
        variables,
        extensions: {}
      }])
    });
    const results = response.json;
    const result = Array.isArray(results) ? results[0] : results;
    if (response.status >= 400) {
      throw new Error(`HTTP error! status: ${response.status}, message: ${JSON.stringify(result)}`);
    }
    if (result.errors) {
      throw new Error(`GraphQL error: ${result.errors.map((e) => e.message).join(", ")}`);
    }
    return result.data;
  }
  async checkConnection() {
    try {
      const query = `
				{
					users {
						profile {
							id
							name
						}
					}
				}
			`;
      await this.makeGraphQLRequest(query);
      return true;
    } catch (error) {
      console.error("Connection check failed:", error);
      return false;
    }
  }
  async getPages() {
    const query = `
			{
				pages {
					list(orderBy: TITLE) {
						id
						path
						title
						createdAt
						updatedAt
					}
				}
			}
		`;
    return await this.makeGraphQLRequest(query);
  }
  async getPageByPath(path) {
    const normalizedPath = path.startsWith("/") ? path.substring(1) : path;
    const query = `
			{
				pages {
					list {
						id
						path
						title
						locale
					}
				}
			}
		`;
    const result = await this.makeGraphQLRequest(query);
    const exactMatch = result.pages.list.find(
      (page) => page.path === normalizedPath
    );
    return exactMatch || null;
  }
  async createPage(path, title, content, description, tags) {
    const mutation = `
      mutation ($content: String!, $description: String!, $editor: String!, $isPrivate: Boolean!, $isPublished: Boolean!, $locale: String!, $path: String!, $publishEndDate: Date, $publishStartDate: Date, $scriptCss: String, $scriptJs: String, $tags: [String]!, $title: String!) {
        pages {
          create(
            content: $content,
            description: $description,
            editor: $editor,
            isPrivate: $isPrivate,
            isPublished: $isPublished,
            locale: $locale,
            path: $path,
            publishEndDate: $publishEndDate,
            publishStartDate: $publishStartDate,
            scriptCss: $scriptCss,
            scriptJs: $scriptJs,
            tags: $tags,
            title: $title
					) {
						responseResult {
							succeeded
							errorCode
							slug
							message
						}
						page {
							id
							path
							title
						}
					}
				}
			}`.trim();
    try {
      const variables = {
        content,
        description: description || "",
        editor: "markdown",
        isPrivate: false,
        isPublished: true,
        locale: "zh",
        path,
        publishEndDate: "",
        publishStartDate: "",
        scriptCss: "",
        scriptJs: "",
        tags: (tags || []).filter((tag) => tag && tag.trim()),
        title
      };
      const result = await this.makeGraphQLRequest(mutation, variables);
      if (result.pages.create.responseResult.succeeded) {
        return {
          success: true,
          message: "Page created successfully",
          pageId: result.pages.create.page.id,
          pageUrl: `${this.settings.wikiUrl}/${path}`
        };
      } else {
        return {
          success: false,
          message: result.pages.create.responseResult.message || "Unknown error occurred"
        };
      }
    } catch (error) {
      return {
        success: false,
        message: `Error creating page: ${error.message}`
      };
    }
  }
  async updatePage(id, path, title, content, description, tags) {
    const normalizedPath = path.startsWith("/") ? path.substring(1) : path;
    const mutation = `
			mutation($id: Int!, $path: String!, $title: String!, $content: String!, $description: String, $tags: [String!]) {
				pages {
					update(
						id: $id
						path: $path
						title: $title
						content: $content
						description: $description
						tags: $tags
						isPublished: true
						isPrivate: false
						publishStartDate: ""
						publishEndDate: ""
						scriptCss: ""
						scriptJs: ""
					) {
						responseResult {
							succeeded
							errorCode
							slug
							message
						}
						page {
							id
							path
							title
						}
					}
				}
			}
		`;
    try {
      const variables = {
        id,
        path: normalizedPath,
        title,
        // content: content.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n'),
        content,
        description: description || "",
        tags: tags || []
      };
      const result = await this.makeGraphQLRequest(mutation, variables);
      if (result.pages.update.responseResult.succeeded) {
        return {
          success: true,
          message: "Page updated successfully",
          pageId: result.pages.update.page.id,
          pageUrl: `${this.settings.wikiUrl}/${normalizedPath}`
        };
      } else {
        return {
          success: false,
          message: result.pages.update.responseResult.message || "Unknown error occurred"
        };
      }
    } catch (error) {
      return {
        success: false,
        message: `Error updating page: ${error.message}`
      };
    }
  }
  /**
   * 获取资源文件夹列表
   * @param parentFolderId 父文件夹 ID（0 表示根目录）
   * @returns 文件夹列表
   */
  async getAssetFolders(parentFolderId = 0) {
    const query = `
			query ($parentFolderId: Int!) {
				assets {
					folders(parentFolderId: $parentFolderId) {
						id
						slug
						name
					}
				}
			}
		`;
    try {
      const result = await this.makeGraphQLRequest(query, { parentFolderId });
      return result.assets.folders || [];
    } catch (error) {
      console.error("Get folders error:", error);
      return [];
    }
  }
  /**
   * 查找指定名称的文件夹 ID
   * @param parentFolderId 父文件夹 ID
   * @param folderName 文件夹名称
   * @returns 文件夹 ID，如果不存在返回 null
   */
  async findFolderIdByName(parentFolderId, folderName) {
    const folders = await this.getAssetFolders(parentFolderId);
    const lowerName = folderName.toLowerCase();
    const folder = folders.find(
      (f) => f.slug.toLowerCase() === lowerName || f.name.toLowerCase() === lowerName
    );
    return folder ? folder.id : null;
  }
  /**
   * 创建资源文件夹
   * @param parentFolderId 父文件夹 ID（0 表示根目录）
   * @param slug 文件夹名称
   * @returns 创建结果，包含新创建的文件夹 ID
   */
  async createAssetFolder(parentFolderId, slug) {
    const mutation = `
			mutation ($parentFolderId: Int!, $slug: String!) {
				assets {
					createFolder(parentFolderId: $parentFolderId, slug: $slug) {
						responseResult {
							succeeded
							errorCode
							slug
							message
						}
					}
				}
			}
		`;
    try {
      const result = await this.makeGraphQLRequest(mutation, { parentFolderId, slug });
      if (result.assets.createFolder.responseResult.succeeded) {
        console.debug(`Asset folder created: ${slug}`);
        const folderId = await this.findFolderIdByName(parentFolderId, slug);
        return {
          succeeded: true,
          folderId: folderId || void 0
        };
      } else {
        return {
          succeeded: false,
          message: result.assets.createFolder.responseResult.message || "Unknown error"
        };
      }
    } catch (error) {
      const err = error;
      console.error("Create folder error:", err);
      return {
        succeeded: false,
        message: err.message
      };
    }
  }
  /**
   * 根据路径创建文件夹结构
   * @param path 完整路径（如 "folder1/folder2/folder3"），将使用所有部分创建文件夹
   * @returns 最终文件夹 ID
   */
  async ensureAssetFolderPath(path) {
    const folderParts = path.split("/").filter((p) => p.trim()).map((p) => p.toLowerCase());
    if (folderParts.length === 0) {
      return 0;
    }
    let currentFolderId = 0;
    for (const folderName of folderParts) {
      let folderId = await this.findFolderIdByName(currentFolderId, folderName);
      if (folderId) {
        console.debug(`Folder already exists: ${folderName} (ID: ${folderId})`);
        currentFolderId = folderId;
      } else {
        const result = await this.createAssetFolder(currentFolderId, folderName);
        if (result.succeeded && result.folderId) {
          console.debug(`Created folder: ${folderName} (ID: ${result.folderId})`);
          currentFolderId = result.folderId;
        } else {
          folderId = await this.findFolderIdByName(currentFolderId, folderName);
          if (folderId) {
            console.debug(`Folder found after retry: ${folderName} (ID: ${folderId})`);
            currentFolderId = folderId;
          } else {
            console.error(`Failed to create or find folder: ${folderName}`);
          }
        }
      }
    }
    return currentFolderId;
  }
  async uploadAsset(fileName, fileContent, folderId = 0) {
    try {
      const formData = new FormData();
      formData.append("mediaUpload", JSON.stringify({ folderId }));
      const getContentType = (name) => {
        const ext = name.toLowerCase().split(".").pop() || "";
        const mimeTypes = {
          "jpg": "image/jpeg",
          "jpeg": "image/jpeg",
          "png": "image/png",
          "gif": "image/gif",
          "webp": "image/webp",
          "svg": "image/svg+xml",
          "bmp": "image/bmp",
          "ico": "image/x-icon",
          "tiff": "image/tiff",
          "tif": "image/tiff",
          "avif": "image/avif",
          "heic": "image/heic",
          "heif": "image/heif"
        };
        return mimeTypes[ext] || "application/octet-stream";
      };
      const sanitizedFileName = fileName.trim();
      if (!sanitizedFileName) {
        throw new Error("File name cannot be empty");
      }
      const contentType = getContentType(sanitizedFileName);
      const blob = new Blob([fileContent], { type: contentType });
      formData.append("mediaUpload", blob, sanitizedFileName);
      console.debug(`Uploading asset: ${sanitizedFileName} to folder ${folderId}`);
      console.debug(`  - Size: ${blob.size} bytes`);
      console.debug(`  - MIME type: ${blob.type}`);
      console.debug(`  - File extension: ${sanitizedFileName.split(".").pop()}`);
      const response = await fetch(`${this.settings.wikiUrl}/u`, {
        method: "POST",
        headers: {
          "Accept": "*/*",
          "Authorization": `Bearer ${this.settings.apiToken}`
          // 注意：不要设置 Content-Type，让浏览器自动设置正确的 boundary
        },
        body: formData
      });
      if (!response.ok) {
        const errorText = await response.text();
        console.error(`Upload failed: ${response.status} - ${errorText}`);
        throw new Error(`HTTP error! status: ${response.status}, message: ${errorText}`);
      }
      console.debug(`\u2705 Asset uploaded successfully: ${sanitizedFileName}`);
      return sanitizedFileName;
    } catch (error) {
      console.error("Asset upload error:", error);
      throw new Error(`Error uploading asset: ${error.message}`);
    }
  }
};

// src/settings.ts
var DEFAULT_SETTINGS = {
  wikiUrl: "",
  apiToken: "",
  autoConvertLinks: true,
  preserveObsidianSyntax: false
};
var WikiJSSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian2.Setting(containerEl).setName("Wiki.js URL").setDesc("The base URL of your Wiki.js instance (e.g., https://wiki.example.com)").addText((text) => text.setPlaceholder("https://wiki.example.com").setValue(this.plugin.settings.wikiUrl).onChange(async (value) => {
      this.plugin.settings.wikiUrl = value.trim();
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("API key").addText((text) => text.setPlaceholder("Enter your API token").setValue(this.plugin.settings.apiToken).onChange(async (value) => {
      this.plugin.settings.apiToken = value.trim();
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("Test connection").setDesc("Test the connection to your wiki.js instance").addButton((button) => button.setButtonText("Test connection").setCta().onClick(async () => {
      button.setButtonText("Testing...");
      button.setDisabled(true);
      try {
        if (!this.plugin.settings.wikiUrl || !this.plugin.settings.apiToken) {
          throw new Error("Please fill in both Wiki.js URL and API token");
        }
        const api = new WikiJSAPI(this.plugin.settings);
        const isConnected = await api.checkConnection();
        if (isConnected) {
          button.setButtonText("\u2705 connected");
          this.plugin.showNotice("Successfully connected to Wiki.js!", 3e3);
        } else {
          button.setButtonText("\u274C failed");
          this.plugin.showNotice("Failed to connect to Wiki.js. Please check your settings.", 5e3);
        }
      } catch (error) {
        button.setButtonText("\u274C error");
        this.plugin.showNotice(`Connection error: ${error.message}`, 5e3);
      }
      setTimeout(() => {
        button.setButtonText("Test connection");
        button.setDisabled(false);
      }, 3e3);
    }));
    new import_obsidian2.Setting(containerEl).setName("Auto convert links").setDesc("Automatically convert relative links to absolute wiki.js paths").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoConvertLinks).onChange(async (value) => {
      this.plugin.settings.autoConvertLinks = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("Preserve Obsidian syntax").setDesc("Keep Obsidian-specific syntax (like [[links]] and callouts) unchanged").addToggle((toggle) => toggle.setValue(this.plugin.settings.preserveObsidianSyntax).onChange(async (value) => {
      this.plugin.settings.preserveObsidianSyntax = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("Advanced").setHeading();
    new import_obsidian2.Setting(containerEl).setName("Upload behavior").setDesc("Choose what happens when uploading a note that already exists in wiki.js").addDropdown((dropdown) => dropdown.addOption("ask", "Ask each time").addOption("update", "Always update existing page").setValue(this.plugin.settings.uploadBehavior || "ask").onChange(async (value) => {
      this.plugin.settings.uploadBehavior = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("Usage").setHeading();
    const usageDiv = containerEl.createDiv();
    usageDiv.createEl("p", { text: "To upload a note to wiki.js:" });
    const ol = usageDiv.createEl("ol");
    ol.createEl("li", { text: "Open the note you want to upload" });
    ol.createEl("li", { text: 'Use the command palette (Ctrl/Cmd + P) and search for "Upload current note"' });
    ol.createEl("li", { text: 'Or right-click the file in the file explorer and select "Upload to wiki.js"' });
    const noteP = usageDiv.createEl("p");
    noteP.createEl("strong", { text: "Note: " });
    noteP.appendText('The plugin will automatically convert Obsidian-specific syntax to be compatible with Wiki.js unless you enable "Preserve Obsidian syntax".');
  }
};

// src/upload-modal.ts
var import_obsidian4 = require("obsidian");

// src/markdown-processor.ts
var MarkdownProcessor = class {
  constructor(settings) {
    this.settings = settings;
  }
  /**
   * Convert Obsidian markdown to Wiki.js compatible markdown
   */
  processMarkdown(content, fileName, pagePath) {
    let processedContent = content;
    let title = this.extractTitle(content, fileName);
    const images = this.extractImages(content);
    console.debug("Extracted images:", JSON.stringify(images, null, 2));
    if (!this.settings.preserveObsidianSyntax) {
      processedContent = this.convertObsidianLinks(processedContent);
      console.debug("Processed pagePath:", pagePath);
      processedContent = this.convertObsidianImages(processedContent, pagePath);
      processedContent = this.convertObsidianTags(processedContent);
      processedContent = this.convertObsidianCallouts(processedContent);
    }
    if (this.settings.autoConvertLinks) {
      processedContent = this.convertInternalLinks(processedContent);
    }
    processedContent = this.normalizeDisplayMathBlocks(processedContent);
    processedContent = this.cleanupObsidianSyntax(processedContent);
    return {
      content: processedContent.trim(),
      title,
      images
    };
  }
  extractTitle(content, fileName) {
    const headingMatch = content.match(/^#\s+(.+)$/m);
    if (headingMatch) {
      return headingMatch[1].trim();
    }
    return fileName.replace(/\.md$/, "").replace(/^\d{4}-\d{2}-\d{2}-/, "");
  }
  convertObsidianLinks(content) {
    return content.replace(/\[\[([^\]|]+)(\|([^\]]+))?\]\]/g, (match, link, pipe, displayText) => {
      if (/\.(png|jpg|jpeg|gif|svg|webp|bmp|ico|tiff|tif|avif|heic|heif)$/i.test(link)) {
        return match;
      }
      const text = displayText || link;
      const url = link.replace(/\s+/g, "-").toLowerCase();
      return `[${text}](/${url})`;
    });
  }
  convertObsidianImages(content, pagePath) {
    return content.replace(/!\[\[([^\]|]+?)(\|([^\]]+))?\]\]/g, (match, imageName, pipe, displayText) => {
      var _a;
      if (!/\.(png|jpg|jpeg|gif|svg|webp|bmp|ico|tiff|tif|avif|heic|heif)$/i.test(imageName)) {
        return match;
      }
      let fileName = ((_a = imageName.split("/").pop()) == null ? void 0 : _a.trim()) || imageName.trim();
      fileName = fileName.replace(/\s+/g, "_");
      fileName = fileName.toLowerCase();
      let imageUrl = "";
      if (pagePath) {
        let cleanPath = (pagePath.startsWith("/") ? pagePath.substring(1) : pagePath).toLowerCase();
        imageUrl = cleanPath ? `/${cleanPath}/${fileName}` : `/${fileName}`;
      } else {
        imageUrl = `/${fileName}`;
      }
      const altText = displayText || fileName;
      return `![${altText}](${imageUrl})`;
    });
  }
  convertObsidianTags(content) {
    return content.replace(/(^|\s)#([a-zA-Z0-9_/-]+)/g, "$1`#$2`");
  }
  convertObsidianCallouts(content) {
    const calloutRegex = /^>\s*\[!(\w+)\]([^\n]*)\n((?:^>.*$\n?)*)/gm;
    return content.replace(calloutRegex, (match, type, title, body) => {
      const cleanBody = body.replace(/^>\s?/gm, "");
      const titleText = title.trim() || type.charAt(0).toUpperCase() + type.slice(1);
      return `> **${titleText}**
>
${cleanBody.split("\n").map((line) => `> ${line}`).join("\n")}
`;
    });
  }
  convertInternalLinks(content) {
    return content.replace(/\[([^\]]+)\]\((?!https?:\/\/)([^)]+)\)/g, (match, text, url) => {
      if (url.startsWith("/")) {
        return match;
      }
      return `[${text}](/${url})`;
    });
  }
  normalizeDisplayMathBlocks(content) {
    return content.replace(/\$\$/g, "\n$$\n").replace(/\n{3,}/g, "\n\n");
  }
  cleanupObsidianSyntax(content) {
    content = content.replace(/^---\n[\s\S]*?\n---\n/, "");
    content = content.replace(/^>\s*\[![^\]]*\]\s*$/gm, "");
    content = content.replace(/\n{3,}/g, "\n\n");
    return content;
  }
  /**
   * Generate a Wiki.js compatible path from the file name
   */
  generatePath(fileName, folderPath) {
    const sanitizeSegment = (segment) => {
      return segment.toLowerCase().replace(/\s+/g, "-").replace(/\./g, "-").replace(/[^\p{L}\p{N}\-_]/gu, "").replace(/-{2,}/g, "-").replace(/^-+|-+$/g, "");
    };
    const slug = sanitizeSegment(fileName.replace(/\.md$/, ""));
    if (!folderPath || folderPath === "/") {
      return slug;
    }
    const cleanFolderPath = folderPath.split("/").map(sanitizeSegment).filter(Boolean).join("/");
    return cleanFolderPath ? `${cleanFolderPath}/${slug}` : slug;
  }
  /**
   * Extract tags from content (YAML frontmatter or inline tags)
   */
  extractTags(content) {
    const tags = [];
    const yamlMatch = content.match(/^---\n([\s\S]*?)\n---/);
    if (yamlMatch) {
      const yamlContent = yamlMatch[1];
      const tagsMatch = yamlContent.match(/^tags:\s*\[(.*?)\]$/m) || yamlContent.match(/^tags:\s*(.+)$/m);
      if (tagsMatch) {
        const tagString = tagsMatch[1];
        if (tagString.includes("[")) {
          const arrayTags = tagString.match(/["']?([^,"']+)["']?/g);
          if (arrayTags) {
            tags.push(...arrayTags.map((tag) => tag.replace(/["']/g, "").trim()));
          }
        } else {
          tags.push(...tagString.split(",").map((tag) => tag.trim()));
        }
      }
    }
    const hashtagMatches = content.match(/(^|\s)#([a-zA-Z0-9_/-]+)/g);
    if (hashtagMatches) {
      hashtagMatches.forEach((match) => {
        const tag = match.trim().substring(1);
        if (tags.indexOf(tag) === -1) {
          tags.push(tag);
        }
      });
    }
    return tags.filter((tag) => tag.length > 0);
  }
  /**
   * Extract images from markdown content
   */
  extractImages(content) {
    const images = [];
    const imageSet = /* @__PURE__ */ new Set();
    const patterns = [
      // 标准 Markdown
      /!\[([^\]]*)\]\(([^)]+)\)/g,
      // Obsidian 格式
      /!\[\[([^\]|]+)(\.[^\]]*)\]\]/g,
      // Obsidian 带标题格式
      /!\[\[([^\]|]+)\|([^\]]+)\]\]/g,
      // HTML <img> 标签
      /<img[^>]+src=["']([^"']+)["'][^>]*>/g
    ];
    for (const pattern of patterns) {
      let match;
      while ((match = pattern.exec(content)) !== null) {
        let path = match[1];
        if (pattern.source.includes("!\\[\\[")) {
          path = match[2] && match[2].startsWith(".") ? match[1] + match[2] : match[1];
        } else if (pattern.source.includes("img")) {
          path = match[1];
        } else {
          path = match[2];
        }
        if (path.startsWith("http://") || path.startsWith("https://") || path.startsWith("data:")) {
          continue;
        }
        path = this.normalizeImagePath(path);
        if (imageSet.has(path)) {
          continue;
        }
        imageSet.add(path);
        const fileName = path.split("/").pop() || path;
        images.push({
          name: fileName,
          path
        });
      }
    }
    return images;
  }
  /**
   * 规范化图片路径
   */
  normalizeImagePath(path) {
    path = path.trim();
    path = path.replace(/\\/g, "/");
    path = path.startsWith("/") ? path.substring(1) : path;
    path = path.replace(/^\.\//, "");
    path = path.split("?")[0].split("#")[0];
    return path;
  }
};

// src/image-tag-processor.ts
var import_obsidian3 = require("obsidian");
var ImageTagProcessor = class {
  constructor(app) {
    this.app = app;
  }
  /**
   * 从图片路径解析出实际的 TFile 对象
   * 参考 obsidian-image-upload-toolkit 的路径解析逻辑
   */
  resolveImageFile(imagePath, sourceFile) {
    var _a;
    const cleanPath = imagePath.split("?")[0].split("#")[0].trim();
    if (cleanPath.startsWith("http://") || cleanPath.startsWith("https://") || cleanPath.startsWith("data:")) {
      return null;
    }
    try {
      const resourcePath = this.app.metadataCache.getFirstLinkpathDest(
        cleanPath,
        sourceFile.path
      );
      if (resourcePath instanceof import_obsidian3.TFile) {
        return resourcePath;
      }
    } catch (error) {
      console.debug("metadataCache method failed:", error);
    }
    let normalizedPath = (0, import_obsidian3.normalizePath)(cleanPath);
    if (normalizedPath.startsWith("/")) {
      normalizedPath = normalizedPath.substring(1);
    }
    let file = this.app.vault.getAbstractFileByPath(normalizedPath);
    if (file instanceof import_obsidian3.TFile) {
      return file;
    }
    if (sourceFile.parent) {
      const parentPath = sourceFile.parent.path;
      let relativePath = cleanPath;
      if (relativePath.startsWith("./")) {
        relativePath = relativePath.substring(2);
      }
      const fullPath = (0, import_obsidian3.normalizePath)(`${parentPath}/${relativePath}`);
      file = this.app.vault.getAbstractFileByPath(fullPath);
      if (file instanceof import_obsidian3.TFile) {
        return file;
      }
      if (cleanPath.startsWith("../")) {
        const parts = cleanPath.split("/");
        let currentPath = parentPath;
        for (const part of parts) {
          if (part === "..") {
            const parent = (_a = this.app.vault.getAbstractFileByPath(currentPath)) == null ? void 0 : _a.parent;
            if (parent) {
              currentPath = parent.path;
            } else {
              break;
            }
          } else if (part !== "." && part !== "") {
            currentPath = (0, import_obsidian3.normalizePath)(`${currentPath}/${part}`);
          }
        }
        file = this.app.vault.getAbstractFileByPath(currentPath);
        if (file instanceof import_obsidian3.TFile) {
          return file;
        }
      }
    }
    const attachmentFolder = this.getAttachmentFolder(sourceFile);
    if (attachmentFolder) {
      const attachmentPath = (0, import_obsidian3.normalizePath)(`${attachmentFolder}/${cleanPath}`);
      file = this.app.vault.getAbstractFileByPath(attachmentPath);
      if (file instanceof import_obsidian3.TFile) {
        return file;
      }
    }
    const fileName = cleanPath.split("/").pop() || cleanPath;
    if (fileName) {
      const allFiles = this.app.vault.getFiles();
      const imageExtensions = [".png", ".jpg", ".jpeg", ".gif", ".svg", ".webp", ".bmp", ".excalidraw"];
      if (sourceFile.parent) {
        const hasExtension2 = fileName.includes(".");
        if (!hasExtension2) {
          for (const ext of imageExtensions) {
            const fileNameWithExt = `${fileName}${ext}`;
            const sameDirFile = allFiles.find(
              (f) => {
                var _a2;
                return f.name === fileNameWithExt && ((_a2 = f.parent) == null ? void 0 : _a2.path) === sourceFile.parent.path;
              }
            );
            if (sameDirFile) {
              return sameDirFile;
            }
          }
        } else {
          const sameDirFile = allFiles.find(
            (f) => {
              var _a2;
              return f.name === fileName && ((_a2 = f.parent) == null ? void 0 : _a2.path) === sourceFile.parent.path;
            }
          );
          if (sameDirFile) {
            return sameDirFile;
          }
        }
      }
      const hasExtension = fileName.includes(".");
      if (!hasExtension) {
        for (const ext of imageExtensions) {
          const fileNameWithExt = `${fileName}${ext}`;
          const foundFile = allFiles.find((f) => f.name === fileNameWithExt);
          if (foundFile) {
            return foundFile;
          }
        }
      } else {
        const foundFile = allFiles.find((f) => f.name === fileName);
        if (foundFile) {
          return foundFile;
        }
      }
    }
    return null;
  }
  /**
   * 获取文件的附件文件夹路径
   * 参考 Obsidian 的附件文件夹设置逻辑
   */
  getAttachmentFolder(sourceFile) {
    if (sourceFile.parent) {
      const parentPath = sourceFile.parent.path;
      const attachmentFolderNames = ["attachments", "assets", "images", "media", "files"];
      for (const folderName of attachmentFolderNames) {
        const folderPath = (0, import_obsidian3.normalizePath)(`${parentPath}/${folderName}`);
        const folder = this.app.vault.getAbstractFileByPath(folderPath);
        if (folder && "children" in folder) {
          return folderPath;
        }
      }
    }
    const commonAttachmentPaths = ["attachments", "assets", "images"];
    for (const path of commonAttachmentPaths) {
      const folder = this.app.vault.getAbstractFileByPath(path);
      if (folder && "children" in folder) {
        return path;
      }
    }
    return null;
  }
  /**
   * 批量解析图片文件
   */
  resolveImageFiles(images, sourceFile) {
    const imageFileMap = /* @__PURE__ */ new Map();
    for (const image of images) {
      const file = this.resolveImageFile(image.path, sourceFile);
      if (file) {
        imageFileMap.set(image.path, file);
      } else {
        console.warn(`Cannot resolve image: ${image.name} (path: ${image.path})`);
      }
    }
    return imageFileMap;
  }
};

// src/upload-modal.ts
var UploadModal = class extends import_obsidian4.Modal {
  constructor(app, plugin, file) {
    super(app);
    this.plugin = plugin;
    this.file = file;
    this.processor = new MarkdownProcessor(plugin.settings);
    this.api = new WikiJSAPI(plugin.settings);
    this.imageProcessor = new ImageTagProcessor(app);
    this.initializeFields().catch((error) => {
      console.error("Failed to initialize upload modal:", error);
      new import_obsidian4.Notice(`Failed to read file: ${error.message}`);
      this.close();
    });
  }
  async initializeFields() {
    var _a, _b;
    const content = await this.app.vault.read(this.file);
    console.log("File parent path:", (_a = this.file.parent) == null ? void 0 : _a.path);
    this.pathInput = this.processor.generatePath(this.file.name, (_b = this.file.parent) == null ? void 0 : _b.path);
    console.log("Generated path:", this.pathInput);
    const processed = this.processor.processMarkdown(content, this.file.name);
    this.titleInput = processed.title;
    this.content = content;
    this.images = processed.images;
    this.tagsInput = this.processor.extractTags(content).join(", ");
    this.descriptionInput = "";
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Upload to wiki.js" });
    const fileInfoDiv = contentEl.createDiv("file-info");
    fileInfoDiv.createEl("p", { text: `File: ${this.file.name}` });
    fileInfoDiv.createEl("p", { text: `Size: ${this.formatFileSize(this.file.stat.size)}` });
    new import_obsidian4.Setting(contentEl).setName("Wiki.js path").setDesc("The path where this page will be created in wiki.js").addText((text) => text.setValue(this.pathInput).onChange((value) => this.pathInput = value));
    new import_obsidian4.Setting(contentEl).setName("Page title").setDesc("The title of the page in wiki.js").addText((text) => text.setValue(this.titleInput).onChange((value) => this.titleInput = value));
    new import_obsidian4.Setting(contentEl).setName("Description").setDesc("Optional description for the page").addTextArea((text) => text.setValue(this.descriptionInput).onChange((value) => this.descriptionInput = value));
    new import_obsidian4.Setting(contentEl).setName("Tags").setDesc("Tags for the page (comma-separated)").addText((text) => text.setValue(this.tagsInput).onChange((value) => this.tagsInput = value));
    const buttonDiv = contentEl.createDiv("modal-button-container");
    const cancelButton = buttonDiv.createEl("button", { text: "Cancel" });
    cancelButton.onclick = () => this.close();
    this.uploadButton = buttonDiv.createEl("button", {
      text: "Upload",
      cls: "mod-cta"
    });
    this.uploadButton.onclick = () => this.performUpload();
    contentEl.addClass("wikijs-upload-modal");
  }
  async uploadImages(images) {
    const imageMap = /* @__PURE__ */ new Map();
    let targetFolderId = 0;
    try {
      targetFolderId = await this.api.ensureAssetFolderPath(this.pathInput.trim());
      console.debug(`Asset folder prepared, folderId: ${targetFolderId}`);
    } catch (error) {
      console.warn("Failed to create asset folder structure:", error);
      targetFolderId = 0;
    }
    const imageFileMap = this.imageProcessor.resolveImageFiles(images, this.file);
    for (const image of images) {
      try {
        console.debug("Processing image:", image.name, "Original path:", image.path);
        const file = imageFileMap.get(image.path);
        if (file instanceof import_obsidian4.TFile) {
          console.debug("Found file:", file.path, "File name:", file.name);
          const arrayBuffer = await this.app.vault.readBinary(file);
          await this.api.uploadAsset(file.name, arrayBuffer, targetFolderId);
          new import_obsidian4.Notice(`\u2705 ${file.name} uploaded successfully`);
          console.debug(`\u2705 Successfully uploaded: ${file.name}`);
        } else {
          console.error(`File not found: ${image.name} (path: ${image.path})`);
          new import_obsidian4.Notice(`Image file not found: ${image.name}`);
        }
      } catch (error) {
        console.error(`Failed to upload image ${image.name}:`, error);
        new import_obsidian4.Notice(`Failed to upload image ${image.name}: ${error.message}`);
      }
    }
    return imageMap;
  }
  replaceImagePaths(content, imageMap) {
    let newContent = content;
    for (const [oldPath, newPath] of imageMap) {
      const escapedOldPath = oldPath.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
      const regex = new RegExp(`!\\[([^\\]]*)\\]\\(${escapedOldPath}\\)`, "g");
      newContent = newContent.replace(regex, `![$1](${newPath})`);
    }
    return newContent;
  }
  async performUpload() {
    if (!this.pathInput.trim()) {
      new import_obsidian4.Notice("Path cannot be empty");
      return;
    }
    if (!this.titleInput.trim()) {
      new import_obsidian4.Notice("Title cannot be empty");
      return;
    }
    this.uploadButton.textContent = "Uploading...";
    this.uploadButton.disabled = true;
    try {
      const existingPage = await this.checkIfPageExists();
      console.debug("Existing page:", existingPage);
      if (existingPage) {
        const shouldUpdate = await this.confirmUpdate(existingPage);
        if (!shouldUpdate) {
          this.uploadButton.textContent = "Upload";
          this.uploadButton.disabled = false;
          return;
        }
      }
      console.debug("Processing markdown with final path:", this.pathInput.trim());
      const finalProcessed = this.processor.processMarkdown(this.content, this.file.name, this.pathInput.trim());
      const processedContent = finalProcessed.content;
      if (this.images && this.images.length > 0) {
        new import_obsidian4.Notice(`Uploading ${this.images.length} images...`);
        await this.uploadImages(this.images);
      }
      let result;
      if (existingPage) {
        const pageId = Number(existingPage.id);
        if (isNaN(pageId)) {
          new import_obsidian4.Notice(`Invalid page ID: ${existingPage.id}`);
          this.uploadButton.textContent = "Upload";
          this.uploadButton.disabled = false;
          return;
        }
        result = await this.api.updatePage(
          pageId,
          this.pathInput.trim(),
          this.titleInput.trim(),
          processedContent,
          this.descriptionInput.trim() || void 0,
          this.parseTags()
        );
      } else {
        result = await this.api.createPage(
          this.pathInput.trim(),
          this.titleInput.trim(),
          processedContent,
          this.descriptionInput.trim() || void 0,
          this.parseTags()
        );
      }
      if (result.success) {
        new import_obsidian4.Notice(`Successfully ${existingPage ? "updated" : "created"} page: ${result.pageUrl}`);
        this.close();
      } else {
        new import_obsidian4.Notice(`Failed to ${existingPage ? "update" : "create"} page: ${result.message}`);
      }
    } catch (error) {
      new import_obsidian4.Notice(`Error uploading page: ${error.message}`);
    } finally {
      this.uploadButton.textContent = "Upload";
      this.uploadButton.disabled = false;
    }
  }
  async checkIfPageExists() {
    try {
      console.debug("Checking if page exists at path:", this.pathInput.trim());
      const page = await this.api.getPageByPath(this.pathInput.trim());
      return page;
    } catch (e) {
      return null;
    }
  }
  async confirmUpdate(existingPage) {
    const behavior = this.plugin.settings.uploadBehavior || "ask";
    if (behavior === "update") {
      return true;
    }
    return new Promise((resolve) => {
      const modal = new import_obsidian4.Modal(this.app);
      modal.titleEl.setText("Page already exists");
      const content = modal.contentEl;
      content.createEl("p", {
        text: `A page already exists at path "${this.pathInput}". What would you like to do?`
      });
      content.createEl("p", {
        text: `Existing page: "${existingPage.title}"`,
        cls: "setting-item-description"
      });
      const buttonDiv = content.createDiv("modal-button-container");
      const cancelButton = buttonDiv.createEl("button", { text: "Cancel" });
      cancelButton.onclick = () => {
        modal.close();
        resolve(false);
      };
      const updateButton = buttonDiv.createEl("button", {
        text: "Update existing",
        cls: "mod-warning"
      });
      updateButton.onclick = () => {
        modal.close();
        resolve(true);
      };
      modal.open();
    });
  }
  parseTags() {
    return this.tagsInput.split(",").map((tag) => tag.trim()).filter((tag) => tag.length > 0);
  }
  formatFileSize(bytes) {
    if (bytes === 0)
      return "0 B";
    const k = 1024;
    const sizes = ["B", "KB", "MB", "GB"];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return parseFloat((bytes / Math.pow(k, i)).toFixed(1)) + " " + sizes[i];
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// main.ts
var NoteToWikiJSPlugin = class extends import_obsidian5.Plugin {
  async onload() {
    await this.loadSettings();
    const ribbonIconEl = this.addRibbonIcon("upload", "Upload current note to wiki.js", (evt) => {
      void this.uploadCurrentNote();
    });
    ribbonIconEl.addClass("wikijs-ribbon-icon");
    this.addCommand({
      id: "upload-current-note",
      name: "Upload current note",
      editorCallback: (editor, view) => {
        void this.uploadCurrentNote();
      }
    });
    this.addCommand({
      id: "upload-file-to-wikijs",
      name: "Upload file",
      callback: () => {
        this.selectAndUploadFile();
      }
    });
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (file instanceof import_obsidian5.TFile && file.extension === "md") {
          menu.addItem((item) => {
            item.setTitle("Upload to wiki.js").setIcon("upload").onClick(async () => {
              await this.uploadFile(file);
            });
          });
        }
      })
    );
    this.addSettingTab(new WikiJSSettingTab(this.app, this));
    const statusBarItemEl = this.addStatusBarItem();
    statusBarItemEl.setText("Wiki.js ready");
    statusBarItemEl.addClass("wikijs-status-bar");
    console.debug("Note to Wiki.js plugin loaded");
  }
  onunload() {
    console.debug("Note to Wiki.js plugin unloaded");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  showNotice(message, duration = 5e3) {
    new import_obsidian5.Notice(message, duration);
  }
  async uploadCurrentNote() {
    const activeFile = this.app.workspace.getActiveFile();
    if (!activeFile) {
      this.showNotice("No active file to upload");
      return;
    }
    if (activeFile.extension !== "md") {
      this.showNotice("Only markdown files can be uploaded to Wiki.js");
      return;
    }
    await this.uploadFile(activeFile);
  }
  async uploadFile(file) {
    if (!this.settings.wikiUrl || !this.settings.apiToken) {
      this.showNotice("Please configure Wiki.js settings first (URL and API Token)");
      return;
    }
    const api = new WikiJSAPI(this.settings);
    const isConnected = await api.checkConnection();
    if (!isConnected) {
      this.showNotice("Cannot connect to Wiki.js. Please check your settings.");
      return;
    }
    const modal = new UploadModal(this.app, this, file);
    modal.open();
  }
  selectAndUploadFile() {
    const files = this.app.vault.getMarkdownFiles();
    if (files.length === 0) {
      this.showNotice("No markdown files found in vault");
      return;
    }
    const modal = new FileSelectionModal(this.app, files, (file) => {
      void this.uploadFile(file);
    });
    modal.open();
  }
  // TODO: Re-enable bulk upload after adding image upload support
  // private async bulkUploadFolder() {
  // 	const folders = this.app.vault.getAllLoadedFiles()
  // 		.filter(file => 'children' in file)
  // 		.map(folder => folder.path);
  // 	if (folders.length === 0) {
  // 		this.showNotice('No folders found in vault');
  // 		return;
  // 	}
  // 	// Create folder selection modal
  // 	const modal = new FolderSelectionModal(this.app, folders, async (folderPath) => {
  // 		await this.uploadFolderContents(folderPath);
  // 	});
  // 	modal.open();
  // }
  // private async uploadFolderContents(folderPath: string) {
  // 	const files = this.app.vault.getMarkdownFiles()
  // 		.filter(file => file.path.startsWith(folderPath));
  // 	if (files.length === 0) {
  // 		this.showNotice(`No markdown files found in folder: ${folderPath}`);
  // 		return;
  // 	}
  // 	const modal = new BulkUploadModal(this.app, this, files);
  // 	modal.open();
  // }
};
var FileSelectionModal = class extends import_obsidian5.Modal {
  constructor(app, files, onFileSelect) {
    super(app);
    this.files = files;
    this.onFileSelect = onFileSelect;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Select file to upload" });
    const fileList = contentEl.createDiv("file-list");
    this.files.forEach((file) => {
      const fileItem = fileList.createDiv("file-item");
      fileItem.createEl("div", { text: file.name, cls: "file-name" });
      fileItem.createEl("div", { text: file.path, cls: "file-path setting-item-description" });
      fileItem.onclick = () => {
        this.close();
        this.onFileSelect(file);
      };
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
